### ISSUE TITLE
matrixfree partial_gpschur 

### ISSUE THREAD

**Issue by rveltz** [RalphAS/PeriodicSchurDecompositions.jl#8]
Hi,

Thanks a lot for your work!

Would it make sense to have a Matrix-free generalized periodic Schur decomposition? How would one provide Bₚ⁻¹? Just Bₚ?

Or maybe it is better to use `partial_pschur` where the user implement `x -> B \ A*x`?

Thanks for your input

**Comment by RalphAS** [comment]
I don't know of a Krylov scheme to handle the generalized problem directly.  So I'd advise a user-implemented `x -> Bₚ \ x` at least, to alternate with the `Aₚ` operators.  (It may be more accurate to separate the `A` and `B` operations.)  Can you afford a sparse direct solver? Otherwise it may be tricky to pick an adequate (but not too expensive) tolerance for an iterative method.

**Comment by rveltz** [comment]
I thought you could do a gmres given that you have the Krylov infrastructure but you are right, better leave this on the user side
